theme: jekyll-theme-cayman
title: Hackathon COVID-19 - Drop Zone des solutions de lutte contre la pandémie
description: Cette page recense toutes les solutions créées ou évoquées lors du [hackathon COVID-19](https://hackathon-covid.fr/) 
